---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: check formatting
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  - name: cargo clippy
    image: rust:1.62-buster
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets --all-features -- -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro

  - name: cargo test
    image: rust:1.62-buster
    commands:
      - cargo test --workspace --no-fail-fast
