pipeline:
  prepare_repo:
    image: rustdocker/rust:nightly
    commands:
      - git submodule init
      - git submodule update

  check_css_js_formatting:
    image: node:alpine
    commands:
      - npm install --save-dev --save-exact prettier
      - ./node_modules/prettier/bin-prettier.js --check assets

  check_rust_formatting:
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  cargo_check:
    image: rust:1.68-buster
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo check
      - cargo check --features embed-lemmy

  cargo_clippy:
    image: rust:1.68-buster
    environment:
      CARGO_HOME: .cargo
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets -- -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro

  cargo_test:
    image: rust:1.68-buster
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432/lemmy
      CARGO_HOME: .cargo
    commands:
      - cargo test --workspace --no-fail-fast

  nightly_build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: lemmynet/lemmybb
      tags:
        - dev
    when:
      event:
        - cron

  publish_release_docker_image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: lemmynet/lemmybb
      auto_tag: true
    when:
      event: tag

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: lemmy
      POSTGRES_PASSWORD: password
