[package]
name = "lemmy_bb"
version = "0.1.0"
edition = "2021"

[dependencies]
rouille = { version = "3.5.0", default-features = false }
maud = "0.23.0"
log = "0.4.16"
env_logger = { version = "0.9.0", default-features = false }
ureq = { version = "2.4.0", features = ["json"] }
lemmy_api_common = { git = "https://github.com/LemmyNet/lemmy.git", branch = "api-derive-default" }
lemmy_db_schema = { git = "https://github.com/LemmyNet/lemmy.git", branch = "api-derive-default" }
once_cell = "1.10.0"
anyhow = "1.0.57"
